It seems that the `cargo` command is not found in the environment. This usually happens because Rust and Cargo are not installed in the Alpine environment. 

Let's update the workflow to install Rust and Cargo in the Alpine build step:

```yaml
name: Build

on: 
  push:
  workflow_dispatch:

jobs:
  build-alpine:
    runs-on: ubuntu-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v2
      - name: Set up Alpine
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu qemu-user-static
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker pull alpine:latest
      - name: Build in Alpine
        run: |
          docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace alpine:latest /bin/sh -c "
          apk add --no-cache build-base musl-dev openssl-dev curl &&
          curl https://sh.rustup.rs -sSf | sh -s -- -y &&
          source $HOME/.cargo/env &&
          cargo build --release"
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: mosquitto-jwt-auth-alpine
          path: ./target/release/libmosquitto_jwt_auth.so
```

This will install Rust and Cargo using Rustup during the Alpine build step.
